### PR TITLE
Exit with error code if remote command failed.

### LINKED ISSUE #110: Exit with error code if remote command errored.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #110.

### CODE REVIEW

File: mainframer.sh [hunk 1]
```diff
@@ -58,6 +58,7 @@ fi
 
 
 BUILD_COMMAND="$@"
+REMOTE_COMMAND_SUCCESSFUL="false"
```
Comment (arturdryomov) [inline mainframer.sh:61]: `BUILD_COMMAND` → `REMOTE_COMMAND`?

**Review by arturdryomov — CHANGES_REQUESTED** [review]

File: mainframer.sh (hunk 1 above)
Comment (artem-zinnatullin) [reply mainframer.sh:61]: in a separate PR

**Review by arturdryomov — APPROVED** [review]
